#pragma once

#include <cstddef>
#include <print>
#include <ostream>
#include <variant>
#include <vector>

#include "../VM/ByteCode.hxx"
#include "../Value/Value.hxx"
#include "../Expr/Expr.hxx"


inline namespace pie {
namespace vm {

using Chunk = std::vector<Code>;

class Compiler {
    // to be generated by the compiler
    Chunk instructions;
    const std::unordered_map<ssize_t, const value::Value> constants;


    void compile(const expr::Node node) {
        std::visit(*this, node);
    }

public:

    Compiler(std::unordered_map<ssize_t, const value::Value> consts) noexcept
    : constants{std::move(consts)}
    { }


    // ============== instructions ============== 

    void emitLoadConst(const ssize_t id) {
        instructions.push_back(Code::LOAD_CONST);
        instructions.push_back(static_cast<Code>(id));
    }


    void emitLoad(const ssize_t id) {
        instructions.push_back(Code::LOAD);
        instructions.push_back(static_cast<Code>(id));
    }


    void emitStore(const ssize_t id) {
        instructions.push_back(Code::STORE);
        instructions.push_back(static_cast<Code>(id));
    }



    void emitPop() {
        if (instructions.size() > 1) {
            switch (instructions[instructions.size() - 2]) { // last thing is the argument, so second to last to get the ins
                case Code::LOAD:
                case Code::LOAD_CONST:
                // pop the argument + the instruction
                instructions.pop_back();
                instructions.pop_back();
                break;

                default:
                // instructions.push_back(Code::POP);
            }
        }
        // else instructions.push_back(Code::POP);
    }


    void emitCall(const ssize_t arg_count) {
        instructions.push_back(Code::CALL);
        instructions.push_back(static_cast<Code>(arg_count));
    }



    // ============== visitor ============== 

    void operator()(const expr::Expr*) { }


    void operator()(const expr::Num* num) {
        // improper name
        if (num->var_ID != -1){
            emitLoad(num->var_ID);
        }
        else {
            emitLoadConst(num->constant_ID);
        }
    }



    void operator()(const expr::Bool *boo) {
        if (boo->var_ID != -1) {
            emitLoad(boo->var_ID);
        }
        else {
            emitLoadConst(boo->constant_ID);
        }
    }



    void operator()(const expr::String *str) {
        if (str->var_ID != -1) {
            emitLoad(str->var_ID);
        }
        else {
            emitLoadConst(str->constant_ID);
        }
    }


    void operator()(const expr::Name *name) {
        emitLoad(name->var_ID);
    }


    void operator()(const expr::Assignment *ass) {
        compile(ass->rhs->variant());
        emitStore(ass->lhs->var_ID);
        emitLoad (ass->lhs->var_ID); // assignments yield their value
    }



    void operator()(const expr::Call *call) {
        compile(call->func->variant());

        for (const auto& arg : call->args) {
            compile(arg->variant());
        }

        emitCall(call->args.size());
    }




    // ============== Utility ============== 
    void output(std::ostream& os) {
        for (size_t i{}; i < instructions.size(); ++i) {
            const auto op = instructions[i];


            switch (op) {
                using enum Code;
                case LOAD:
                case STORE:
                case LOAD_CONST:
                case CALL:
                    std::println(os, "{} {}", stringify(op), static_cast<size_t>(instructions[++i]));
                break;

                default:
                    std::println(os, "{}", stringify(op));
            }
        }
    }
};


// compiling: By Sabeeha
/*

*/


} // namespace vm
} // namespace pie
