#pragma once

#include <cstddef>
#include <print>
#include <ostream>
#include <string_view>
#include <variant>
#include <vector>

#include "../VM/ByteCode.hxx"
#include "../Value/Value.hxx"
#include "../Expr/Expr.hxx"


namespace pie {
namespace vm {

using Chunk = std::vector<Code>;

class Compiler {
    // to be generated by the compiler
    Chunk instructions;
    const std::unordered_map<ssize_t, const value::Value> constants;


    void compile(const expr::Node node) {
        std::visit(*this, node);
    }

public:

    Compiler(std::unordered_map<ssize_t, const value::Value> consts) noexcept
    : constants{std::move(consts)}
    { }


    Chunk getInstructions() const noexcept { return instructions; }


    // ============== instructions ============== 


    void emitID(const ssize_t id) {
        instructions.push_back(static_cast<Code>(id));
    }

    void emitLoadConst(const ssize_t id) {
        instructions.push_back(Code::LOAD_CONST);
        emitID(id);
    }


    void emitLoadGlobal(const ssize_t id) {
        instructions.push_back(Code::LOAD_GLOBAL);
        emitID(id);
    }


    void emitLoad(const ssize_t id) {
        instructions.push_back(Code::LOAD);
        emitID(id);
    }


    void emitStore(const ssize_t id) {
        instructions.push_back(Code::STORE);
        emitID(id);
    }



    void emitPop() {
        if (instructions.size() > 1) {
            switch (instructions[instructions.size() - 2]) { // last thing is the argument, so second to last to get the ins
                case Code::LOAD:
                case Code::LOAD_CONST:
                // pop the argument + the instruction
                instructions.pop_back();
                instructions.pop_back();
                break;

                default:;
                // instructions.push_back(Code::POP);
            }
        }
        // else instructions.push_back(Code::POP);
    }


    void emitCall(const ssize_t arg_count) {
        instructions.push_back(Code::CALL);
        instructions.push_back(static_cast<Code>(arg_count));
    }



    void halt() { instructions.push_back(Code::HALT); }

    // ============== visitor ============== 


    void operator()(const expr::Expr*) { }


    void operator()(const expr::Num* num) {
        // improper name
        if (num->var_ID != -1){
            emitLoad(num->var_ID);
        }
        else {
            emitLoadConst(num->constant_ID);
        }
    }



    void operator()(const expr::Bool *boo) {
        if (boo->var_ID != -1) {
            emitLoad(boo->var_ID);
        }
        else {
            emitLoadConst(boo->constant_ID);
        }
    }



    void operator()(const expr::String *str) {
        if (str->var_ID != -1) {
            emitLoad(str->var_ID);
        }
        else {
            emitLoadConst(str->constant_ID);
        }
    }


    void operator()(const expr::Name *name) {
        if (isGlobal(name->name)) {
            emitLoadGlobal(name->var_ID);
        }
        else {
            emitLoad(name->var_ID);
        }
    }


    void operator()(const expr::Assignment *ass) {
        compile(ass->rhs->variant());
        emitStore(ass->lhs->var_ID);
        emitLoad (ass->lhs->var_ID); // assignments yield their value
    }



    void operator()(const expr::Call *call) {
        compile(call->func->variant());

        for (const auto& arg : call->args) {
            compile(arg->variant());
        }

        emitCall(call->args.size());
    }



    void operator()(const expr::Loop *loop) {
        if (loop->kind) {
            compile(loop->kind->variant());
        }
        else {

        }
    }



    // ============== Utility ============== 
    void output(std::ostream& os) {
        for (size_t i{}; i < instructions.size(); ++i) {
            const auto op = instructions[i];


            switch (op) {
                using enum Code;
                case LOAD:
                case STORE:
                case LOAD_CONST:
                case LOAD_GLOBAL:
                case CALL:
                    std::println(os, "{} {}", stringify(op), static_cast<size_t>(instructions[++i]));
                break;

                default:
                    std::println(os, "{}", stringify(op));
            }
        }
    }


    bool isGlobal(const std::string_view name) {
        for (const auto& g : GS)
            if (name == value::stringify(g)) return true;

        return false;
    }

    inline static const std::initializer_list<value::Value> GS = {
        type::builtins::Any(),
        type::builtins::Int(),
        type::builtins::Double(),
        type::builtins::String(),
        type::builtins::Bool(),
        type::builtins::Syntax(),
        type::builtins::Type(),


        value::BuiltinFunction{"__builtin_rand_int"},

        value::BuiltinFunction{"__builtin_print"      },
        value::BuiltinFunction{"__builtin_concat"     },
        value::BuiltinFunction{"__builtin_print_env"  },
        value::BuiltinFunction{"__builtin_panic"      },
        value::BuiltinFunction{"__builtin_id"         },
        value::BuiltinFunction{"__builtin_input_str"  },
        value::BuiltinFunction{"__builtin_input_int"  },
        value::BuiltinFunction{"__builtin_decltype"   },
        value::BuiltinFunction{"__builtin_type"       },
        value::BuiltinFunction{"__builtin_len"        },
        value::BuiltinFunction{"__builtin_reset"      },
        value::BuiltinFunction{"__builtin_eval"       },
        value::BuiltinFunction{"__builtin_neg"        },
        value::BuiltinFunction{"__builtin_abs"        },
        value::BuiltinFunction{"__builtin_not"        },
        value::BuiltinFunction{"__builtin_to_int"     },
        value::BuiltinFunction{"__builtin_to_double"  },
        value::BuiltinFunction{"__builtin_to_string"  },
        value::BuiltinFunction{"__builtin_get"        },
        value::BuiltinFunction{"__builtin_push"       },
        value::BuiltinFunction{"__builtin_push"       },
        value::BuiltinFunction{"__builtin_pop"        },
        value::BuiltinFunction{"__builtin_pop_front"  },
        value::BuiltinFunction{"__builtin_add"        },
        value::BuiltinFunction{"__builtin_sub"        },
        value::BuiltinFunction{"__builtin_mul"        },
        value::BuiltinFunction{"__builtin_div"        },
        value::BuiltinFunction{"__builtin_mod"        },
        value::BuiltinFunction{"__builtin_pow"        },
        value::BuiltinFunction{"__builtin_gt"         },
        value::BuiltinFunction{"__builtin_geq"        },
        value::BuiltinFunction{"__builtin_eq"         },
        value::BuiltinFunction{"__builtin_leq"        },
        value::BuiltinFunction{"__builtin_lt"         },
        value::BuiltinFunction{"__builtin_and"        },
        value::BuiltinFunction{"__builtin_or"         },
        value::BuiltinFunction{"__builtin_set"        },
        value::BuiltinFunction{"__builtin_conditional"},
        value::BuiltinFunction{"__builtin_str_slice"  },
        value::BuiltinFunction{"__builtin_str_split"  },

        //* File IO
        value::BuiltinFunction{"__builtin_open_file" },
        value::BuiltinFunction{"__builtin_close_file"},
        value::BuiltinFunction{"__builtin_read_file" },
        value::BuiltinFunction{"__builtin_read_line" },
        value::BuiltinFunction{"__builtin_read_word" },

        //* FFI shit
        value::BuiltinFunction{"__builtin_dlopen"          },
        value::BuiltinFunction{"__builtin_dlsym"           },
        value::BuiltinFunction{"__builtin_ffi_call"        },
        value::BuiltinFunction{"__builtin_ffi_type_void"   },
        value::BuiltinFunction{"__builtin_ffi_type_int"    },
        value::BuiltinFunction{"__builtin_ffi_type_float"  },
        value::BuiltinFunction{"__builtin_ffi_type_double" },
        value::BuiltinFunction{"__builtin_ffi_type_uint8"  },
        value::BuiltinFunction{"__builtin_ffi_type_sint8"  },
        value::BuiltinFunction{"__builtin_ffi_type_uint16" },
        value::BuiltinFunction{"__builtin_ffi_type_sint16" },
        value::BuiltinFunction{"__builtin_ffi_type_uint32" },
        value::BuiltinFunction{"__builtin_ffi_type_sint32" },
        value::BuiltinFunction{"__builtin_ffi_type_uint64" },
        value::BuiltinFunction{"__builtin_ffi_type_sint64" },
        value::BuiltinFunction{"__builtin_ffi_type_struct" },
        value::BuiltinFunction{"__builtin_ffi_type_pointer"},
        value::BuiltinFunction{"__builtin_ffi_type_cstring"},
        value::BuiltinFunction{"__builtin_ffi_type_complex"},

        value::BuiltinFunction{"__builtin_ptr_to_string"},
    };
};


// compiling: By Sabeeha
/*

*/


} // namespace vm
} // namespace pie
